SET DEFINE OFF; 

CREATE SEQUENCE OPI_SEQ
  START WITH 1
  MAXVALUE 9999
  MINVALUE 1
  CYCLE
  NOCACHE
  NOORDER;
  
  
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0671778U', '67045', 'STRASBOURG CEDEX', '1 PLACE D ATHENES BP 66', NULL, 
    NULL, 'Universit� Strasbourg 3');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0671712X', '67070', 'STRASBOURG CEDEX', '4 RUE BLAISE PASCAL BP1032 F', NULL, 
    NULL, 'Universit� Strasbourg 1');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0671713Y', '67084', 'STRASBOURG CEDEX', '22, RUE DESCARTES', NULL, 
    NULL, 'Universit� Strasbourg 2');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0673021V', '67000', 'STRASBOURG', '4 rue Blaise Pascal', NULL, 
    NULL, 'Universit� de Strasbourg');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0772502B', '77454', 'MARNE LA VALLEE CEDEX 2', '5, Boulevard Descartes', 'Champs sur Marne', 
    NULL, 'UNIVERSITE DE MARNE LA VALLEE');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0730858L', '73011', 'CHAMBERY CEDEX', '27 RUE MARCOZ BP 1104', NULL, 
    NULL, 'Universit� de Chambery');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0781944P', '78035', 'VERSAILLES CEDEX', '23, RUE DU REFUGE', NULL, 
    NULL, 'Universit� de Versailles');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0900384D', '90010', 'BELFORT CEDEX', 'RUE DU CHATEAU', NULL, 
    NULL, 'INSTITUT POLYTECHNIQUE DE SEVENANS');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0900424X', '90010', 'BELFORT CEDEX', '10 RUE DU CHATEAU', NULL, 
    NULL, 'UNIVERSITE DE TECHNOLOGIE DE BELFORT MONTBELIARD');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0830766G', '83957', 'LA GARDE CEDEX', 'AVENUE DE L UNIVERSITE  BP 132', NULL, 
    NULL, 'Universit� de Toulon');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0911101C', '91405', 'ORSAY CEDEX', '15, RUE GEORGES CLEMENCEAU', NULL, 
    NULL, 'Universit� Paris 11');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0921204J', '92001', 'NANTERRE CEDEX', '200 AVENUE DE LA REPUBLIQUE', NULL, 
    NULL, 'Universit� Paris 10');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0932056E', '93160', 'NOISY LE GRAND', '2 RUE DE LA BUTTE VERTE', NULL, 
    NULL, 'Universit� de Marne la Vall�e');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0931827F', '93526', 'ST DENIS CEDEX', '2 RUE DE LA LIBERTE', NULL, 
    NULL, 'Universit� de Paris 8');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0931238R', '93430', 'VILLETANEUSE', 'AVENUE JEAN-BAPTISTE CLEMENT', NULL, 
    NULL, 'Universit� Paris 13');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0911975C', '91025', 'EVRY CEDEX', '23 BOULEVARD DES COQUIBUS', NULL, 
    NULL, 'Universit� Evry');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0840685N', '84010', 'AVIGNON CEDEX 1', '35 RUE JOSEPH VERNET   BP 218', NULL, 
    NULL, 'Universit� d''Avignon');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0801344B', '80025', 'AMIENS CEDEX 1', 'CHEMIN DU THIL', NULL, 
    NULL, 'Universit� d''Amiens');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0941111X', '94010', 'CRETEIL CEDEX', '61, AVENUE DU GENERAL DE GAULLE', NULL, 
    NULL, 'Universit� Paris 12');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0341087X', '34006', 'MONTPELLIER CEDEX 1', '5,BD HENRI IV', 'BP 1017', 
    NULL, 'Universit� Montpellier 1');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0341089Z', '34032', 'MONTPELLIER CEDEX 1', 'B P  5043', 'ROUTE DE MENDE', 
    NULL, 'Universit� Montpellier 3');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0341088Y', '34095', 'MONTPELLIER CEDEX 5', 'PLACE EUGENE BATAILLON', NULL, 
    NULL, 'Universit� Montpellier 2');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0290346U', '29269', 'BREST CEDEX 1', 'RUE DES ARCHIVES BP 137', NULL, 
    NULL, 'Universit� de Brest');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0331765P', '33076', 'BORDEAUX CEDEX', '146, RUE LEO SAIGNAT', NULL, 
    NULL, 'Universit� Bordeaux 2');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0350936C', '35014', 'RENNES CEDEX 7', '2 RUE DU THABOR BP 1134', NULL, 
    NULL, 'Universit� Rennes 1');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0350937D', '35043', 'RENNES CEDEX', '6, AVENUE GASTON BERGER', NULL, 
    NULL, 'Universit� Rennes 2');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('9740478B', '97489', 'ST DENIS CEDEX', '15 AVENUE RENE CASSIN', 'STE CLOTILDE', 
    NULL, 'Universit� de la R�union');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0171463Y', '17071', 'LA ROCHELLE CEDEX 9', '23 AVENUE ALBERT EINSTEIN', NULL, 
    NULL, 'Universit� de la Rochelle');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0332929E', '33608', 'PESSAC CEDEX', 'AVENUE LEON DUGUIT', NULL, 
    NULL, 'UNIVERSITE BORDEAUX 4');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0132364Z', '13628', 'AIX EN PROVENCE CEDEX 1', '3, AVENUE ROBERT SCHUMAN', NULL, 
    NULL, 'Universit� Aix-Marseille 3');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0131842G', '13331', 'MARSEILLE CEDEX 03', '3, PLACE VICTOR-HUGO', NULL, 
    NULL, 'Universit� Aix-Marseille 1');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0131843H', '13284', 'MARSEILLE CEDEX 07', '58 BD CHARLES LIVON', NULL, 
    NULL, 'Universit� Aix-Marseille 2');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('9710585J', '97159', 'POINTE A PITRE CEDEX', 'BD LEGITIMUS BP 771', NULL, 
    NULL, 'Universit�  Antilles Guyane');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0720916E', '72017', 'LE MANS CEDEX 1', 'AV  MESSIAEN   BP 535', NULL, 
    NULL, 'Universit� du Mans');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0101060Y', '10010', 'TROYES CEDEX', '13 BD HENRI BARBUSSE BP 2060', NULL, 
    NULL, 'Universit� de Troyes');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('7200664J', '20250', 'CORTE', '7  AV J NICOLI BP 52', NULL, 
    NULL, 'Universit� de Corse');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0251215K', '25030', 'BESANCON CEDEX', '3 RUE GOUDIMEL', NULL, 
    NULL, 'Universit� de Besancon');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0331764N', '33405', 'TALENCE CEDEX', '351, COURS DE LA LIBERATION', NULL, 
    NULL, 'Universit� Bordeaux 1');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0331766R', '33405', 'TALENCE CEDEX', 'ESPLANADE MONTAIGNE DOM UNIV', NULL, 
    NULL, 'Universit� Bordeaux 3');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0211237F', '21004', 'DIJON CEDEX', 'CAMPUS UNIV MONTMUZARD BP 138', NULL, 
    NULL, 'Universit� de Dijon');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0141408E', '14032', 'CAEN CEDEX 5', 'ESPLANADE DE LA PAIX', NULL, 
    NULL, 'Universit� de Caen');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0060931E', '06034', 'NICE CEDEX 1', '28, AVENUE VALROSE', NULL, 
    NULL, 'Universit� de Nice');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0311381H', '31006', 'TOULOUSE CEDEX 6', 'PLACE DES HAUTS MURATS', 'BP 354', 
    NULL, 'INSTITUT NATIONAL POLYTECHNIQUE DE TOULOUSE');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0311382J', '31042', 'TOULOUSE CEDEX 9', 'PLACE ANATOLE FRANCE', NULL, 
    NULL, 'Universit� Toulouse 1');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0311383K', '31058', 'TOULOUSE CEDEX 9', '5, ALLEE ANTONIO MACHADO', NULL, 
    NULL, 'Universit� Toulouse 2');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0311384L', '31062', 'TOULOUSE CEDEX 9', '118, ROUTE DE NARBONNE', NULL, 
    NULL, 'Universit� Toulouse 3');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0310155A', '31000', 'TOULOUSE', '31 rue de la Fonderie', NULL, 
    NULL, 'UNIVERSITE CATHOLIQUE DE TOULOUSE');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0601223D', '60206', 'COMPIEGNE CEDEX', 'RUE ROGER COUTTOLENC BP 649', NULL, 
    NULL, 'Universit� de Compi�gne');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0640251A', '64012', 'PAU CEDEX', 'AV  DE L UNIVERSITE BP 576', NULL, 
    NULL, 'Universit� de Pau et Pays de l''Adour');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0421095M', '42023', 'ST ETIENNE CEDEX 2', '34 RUE FRANCIS BAULIER', NULL, 
    NULL, 'Universit� de Saint-Etienne');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0370800U', '37041', 'TOURS CEDEX 1', '3, RUE DES TANNEURS', NULL, 
    NULL, 'Universit� de Tours');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0381912X', '38031', 'GRENOBLE CEDEX 1', '46 AVENUE FELIX VIALLET', NULL, 
    NULL, 'INSTITUT NATIONAL POLYTECHNIQUE DE GRENOBLE');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0381840U', '38040', 'GRENOBLE CEDEX 9', 'DOM UNIV AVE CENTRALE BP 25', NULL, 
    NULL, 'Universit� Grenoble 3');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0381838S', '38041', 'GRENOBLE CEDEX 9', '621 AV CENTRALE BP53X', NULL, 
    NULL, 'Universit� Grenoble 1');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0541564G', '54501', 'VANDOEUVRE LES NANCY CEDEX', '2 AVENUE DE LA FORET DE HAYE', 'BP 3', 
    NULL, 'INSTITUT NATIONAL POLYTECHNIQUE DE NANCY');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0561718N', '56000', 'VANNES', '12 AVENUE SAINT SYMPHORIEN', NULL, 
    NULL, 'UNIVERSITE DE BRETAGNE SUD');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0623957P', '62030', 'ARRAS CEDEX', '9 RUE DU TEMPLE BP 10665', NULL, 
    NULL, 'Universit� d''Artois');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0631262E', '63001', 'CLERMONT FERRAND CEDEX 1', '49 BOULEVARD GERGOVIA BP 32', NULL, 
    NULL, 'Universit� Clermont-Ferrand 1');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0631525R', '63006', 'CLERMONT FERRAND CEDEX 1', '34 AVENUE CARNOT BP 185', NULL, 
    NULL, 'Universit� Clermont-Ferrand 2');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0681166Y', '68093', 'MULHOUSE CEDEX 2', '2, RUE DES FRERES LUMIERE', NULL, 
    NULL, 'Universit� de Mulhouse');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0381839T', '38402', 'ST MARTIN D HERES CEDEX', 'DOMAINE UNIVERSITAIRE BP 47X', NULL, 
    NULL, 'Universit� Grenoble 2');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0470940S', '47931', 'AGEN CEDEX 9', 'AGROPOLE ROUTE DE CONDOM', 'BP 119', 
    NULL, 'UNIVERSITE THEMATIQUE AGEN');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0511296G', '51097', 'REIMS CEDEX', 'VILLA DOUCE 9 BD DE LA PAIX', NULL, 
    NULL, 'Universit� de Reims');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0595964M', '59375', 'DUNKERQUE CEDEX 1', '1 PLACE DE L''YSER BP 1022', NULL, 
    NULL, 'Universit� Littoral');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0572081C', '57012', 'METZ CEDEX 01', 'ILE DU SAULCY BP 794', NULL, 
    NULL, 'Universit� de Metz');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0593560Z', '59800', 'LILLE', '42, RUE PAUL DUEZ', NULL, 
    NULL, 'Universit� Lille 2');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0590344D', '59800', 'LILLE', '60, Boulevard Vauban', NULL, 
    NULL, 'UNIVERSITE CATHOLIQUE DE LILLE');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0440984F', '44035', 'NANTES CEDEX 1', 'QUAI TOURVILLE   BP 1026', NULL, 
    NULL, 'Universit� de Nantes');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0692437Z', '69239', 'LYON CEDEX 02', '1 RUE UNIVERSITE BP 0638', NULL, 
    NULL, 'Universit� Lyon 3');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0690195M', '69002', 'LYON', '25, Rue Plat', NULL, 
    NULL, 'UNIVERSITE CATHOLIQUE DE LYON');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0691775E', '69365', 'LYON CEDEX 07', '86, RUE PASTEUR', NULL, 
    NULL, 'Universit� Lyon 2');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0691774D', '69622', 'VILLEURBANNE CEDEX', '43 BD DU 11 NOV 1918 BP 761', NULL, 
    NULL, 'Universit� Lyon 1');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0593279U', '59304', 'VALENCIENNES CEDEX', 'LE MONT HOUY BP 311', NULL, 
    NULL, 'Universit� de Valenciennes');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0593561A', '59653', 'VILLENEUVE D ASCQ CEDEX', 'DOM  UNIV  PONT DE BOIS  BP 60149', NULL, 
    NULL, 'Universit� SHS Lille 3 - Charles de Gaulle');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0593559Y', '59655', 'VILLENEUVE D ASCQ CEDEX', 'DOM UNIVERSITAIRE SCIENTIFIQUE', NULL, 
    NULL, 'Universit� Lille 1');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0660437S', '66860', 'PERPIGNAN CEDEX 9', '52 AVENUE DE VILLENEUVE', NULL, 
    NULL, 'Universit� de Perpignan');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0450855K', '45067', 'ORLEANS CEDEX 2', 'CHATEAU DE LA SOURCE', 'BP 6749', 
    NULL, 'Universit� d''Orl�ans');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0541508W', '54001', 'NANCY CEDEX', '25, RUE BARON LOUIS BP 454', NULL, 
    NULL, 'Universit� Nancy 2');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0541507V', '54013', 'NANCY CEDEX', '24 30 R LIONNOIS BP 3069', NULL, 
    NULL, 'Universit� Nancy 1');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0490970N', '49035', 'ANGERS CEDEX 01', 'RUE DES ARENES BP 3532', NULL, 
    NULL, 'Universit� d''Angers');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0490811R', '49000', 'ANGERS', '3, Place Andr� Leroy', NULL, 
    NULL, 'UNIVERSITE CATHOLIQUE DE L''OUEST');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0762762P', '76063', 'LE HAVRE CEDEX', '25 RUE PHILIPPE LEBON BP 1123', NULL, 
    NULL, 'Universit� du Havre');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0951793H', '95011', 'CERGY PONTOISE CEDEX', '33 BD DU PORT BP 220', NULL, 
    NULL, 'Universit� de Cergy-Pontoise');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('9830445S', '98847', 'NOUMEA CEDEX', 'BP 4477', '98847 NOUMEA', 
    NULL, 'UNIVERSITE DE NOUVELLE CALEDONIE');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('9840303G', '98800', 'NOUMEA', 'B P  4635  PAPEETE', NULL, 
    NULL, 'Universit� Francaise du Pacifique');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0751719L', '75230', 'PARIS CEDEX 05', '17, PLACE DE LA SORBONNE', NULL, 
    NULL, 'Universit� Paris 3');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0751720M', '75230', 'PARIS CEDEX 05', '1, RUE VICTOR COUSIN', NULL, 
    NULL, 'Universit� Paris 4');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0751717J', '75231', 'PARIS CEDEX 05', '12 PLACE DU PANTHEON', NULL, 
    NULL, 'Universit� Paris 1');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0751718K', '75231', 'PARIS CEDEX 05', '12, PLACE DU PANTHEON', NULL, 
    NULL, 'Universit� Paris 2');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0751723R', '75251', 'PARIS CEDEX 05', '2,PLACE JUSSIEU', NULL, 
    NULL, 'Universit� Paris 7');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0751722P', '75252', 'PARIS CEDEX 05', '4, PLACE JUSSIEU', NULL, 
    NULL, 'Universit� Paris 6');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0753428U', '75252', 'PARIS CEDEX 05', '4 PLACE JUSSIEU', NULL, 
    NULL, 'INSTITUT DE PHYSIQUE DU GLOBE DE PARIS');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0751721N', '75270', 'PARIS CEDEX 06', '12 RUE DE L ECOLE DE MEDECINE', NULL, 
    NULL, 'Universit� Paris 5');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0753541S', '75006', 'PARIS', '21, Rue Assas', NULL, 
    NULL, 'UNIVERSITE CATHOLIQUE DE PARIS');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0753431X', '75341', 'PARIS CEDEX 07', '27 RUE SAINT GUILLAUME', NULL, 
    NULL, 'INSTITUT D''ETUDES POLITIQUES DE PARIS');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0753488J', '75343', 'PARIS CEDEX 07', '2 RUE DE LILLE', NULL, 
    NULL, 'I.N.A.L.C.O. DE PARIS');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0753496T', '75014', 'PARIS', '61 AVENUE DE L''OBSERVATOIRE', NULL, 
    NULL, 'OBSERVATOIRE DE PARIS');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0750736T', '75775', 'PARIS CEDEX 16', 'PLACE DU MARECHAL DE TASSIGNY', NULL, 
    NULL, 'Universit� Paris 9');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('9840349G', '98702', 'FAAA CEDEX', 'BP 6570', 'Faa''a - A�roport', 
    'Tahiti', 'UNIVERSITE DE POLYNESIE FRANCAISE');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0860856N', '86034', 'POITIERS CEDEX', '15 RUE DE L HOTEL DIEU', NULL, 
    NULL, 'Universit� de Poitiers');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0870669E', '87065', 'LIMOGES CEDEX 2', 'HOTEL BURGY 13 RUE DE GENEVE', NULL, 
    NULL, 'Universit� de Limoges');
Insert into ETABLISSEMENT
   (COD_ETB, COD_POS_ADR_ETB, LIB_ACH, LIB_AD1_ETB, LIB_AD2_ETB, 
    LIB_AD3_ETB, LIB_OFF_ETB)
 Values
   ('0761904G', '76821', 'MONT ST AIGNAN CEDEX', '1, RUE THOMAS BECKET', NULL, 
    NULL, 'Universit� de Rouen');

Insert into ETAT_DOSSIER
   (ID_ETAT_DOSSIER, LIB_COURT, LIB_LONG)
 Values
   (1, 'C', 'Complet');
Insert into ETAT_DOSSIER
   (ID_ETAT_DOSSIER, LIB_COURT, LIB_LONG)
 Values
   (2, 'I', 'Incomplet');

Insert into DECISION_DOSSIER
   (ID_DECISION_DOSSIER, LIB_COURT, LIB_LONG)
 Values
   (1, 'AD', 'Avis d�favorable');
Insert into DECISION_DOSSIER
   (ID_DECISION_DOSSIER, LIB_COURT, LIB_LONG)
 Values
   (2, 'AF', 'Avis favorable');
Insert into DECISION_DOSSIER
   (ID_DECISION_DOSSIER, LIB_COURT, LIB_LONG)
 Values
   (3, 'AUFR', 'En attente avis d''UFR');
Insert into DECISION_DOSSIER
   (ID_DECISION_DOSSIER, LIB_COURT, LIB_LONG)
 Values
   (4, 'AS', 'En attente de signature');
Insert into DECISION_DOSSIER
   (ID_DECISION_DOSSIER, LIB_COURT, LIB_LONG)
 Values
   (5, 'AV', 'En attente de validation');
Insert into DECISION_DOSSIER
   (ID_DECISION_DOSSIER, LIB_COURT, LIB_LONG)
 Values
   (6, 'AP', 'En attente de pi�ces');

Insert into LOCALISATION_DOSSIER
   (ID_LOCALISATION_DOSSIER, LIB_COURT, LIB_LONG)
 Values
   (1, 'E', 'Envoy� � l''�tudiant');
Insert into LOCALISATION_DOSSIER
   (ID_LOCALISATION_DOSSIER, LIB_COURT, LIB_LONG)
 Values
   (2, 'Scol', 'Service Scolarit�');
   
Insert into PARAMETRES
   (CODE, ETAT, COMMENTAIRE)
 Values
   ('date_export_bu', 1, '12/09/2012 22:00:17');
Insert into PARAMETRES
   (CODE, ETAT, COMMENTAIRE)
 Values
   ('ouvertureAccueil', 1, 'Bla bla bla accueil');
Insert into PARAMETRES
   (CODE, ETAT, COMMENTAIRE)
 Values
   ('ouvertureDepart', 1, 'L''application Transfert-d�part sera ferm�e du mercredi 25 juillet au mardi 21 ao�t inclus.<br/><br/>Merci de votre compr�hension.<br/>');

  
Insert into ACCUEIL_RESULTAT
   (ID_ACCUEIL_RESULTAT, LIBELLE)
 Values
   (2, 'R�sultat inconnu');
Insert into ACCUEIL_RESULTAT
   (ID_ACCUEIL_RESULTAT, LIBELLE)
 Values
   (3, 'AJAC / Chevauchement');
Insert into ACCUEIL_RESULTAT
   (ID_ACCUEIL_RESULTAT, LIBELLE)
 Values
   (4, 'Ajourn�');
Insert into ACCUEIL_RESULTAT
   (ID_ACCUEIL_RESULTAT, LIBELLE)
 Values
   (1, 'Admis');

Insert into ACCUEIL_ANNEE
   (ID_ACCUEIL_ANNEE, LIBELLE)
 Values
   (11, '2012/2013');   
Insert into ACCUEIL_ANNEE
   (ID_ACCUEIL_ANNEE, LIBELLE)
 Values
   (2, '2003/2004');
Insert into ACCUEIL_ANNEE
   (ID_ACCUEIL_ANNEE, LIBELLE)
 Values
   (3, '2004/2005');
Insert into ACCUEIL_ANNEE
   (ID_ACCUEIL_ANNEE, LIBELLE)
 Values
   (4, '2005/2006');
Insert into ACCUEIL_ANNEE
   (ID_ACCUEIL_ANNEE, LIBELLE)
 Values
   (5, '2006/2007');
Insert into ACCUEIL_ANNEE
   (ID_ACCUEIL_ANNEE, LIBELLE)
 Values
   (6, '2007/2008');
Insert into ACCUEIL_ANNEE
   (ID_ACCUEIL_ANNEE, LIBELLE)
 Values
   (7, '2008/2009');
Insert into ACCUEIL_ANNEE
   (ID_ACCUEIL_ANNEE, LIBELLE)
 Values
   (8, '2009/2010');
Insert into ACCUEIL_ANNEE
   (ID_ACCUEIL_ANNEE, LIBELLE)
 Values
   (9, '2010/2011');
Insert into ACCUEIL_ANNEE
   (ID_ACCUEIL_ANNEE, LIBELLE)
 Values
   (10, '2011/2012');
Insert into ACCUEIL_ANNEE
   (ID_ACCUEIL_ANNEE, LIBELLE)
 Values
   (1, '2002/2003');   
    
COMMIT;